# Generated by Django 4.2 on 2023-04-30 20:19

import django.contrib.postgres.fields
from django.db import migrations, models
import recipe.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("food", models.CharField(default="", max_length=80)),
                ("food_type", models.CharField(default="", max_length=50)),
                ("description", models.CharField(max_length=300)),
                ("picture", models.ImageField(blank=True, null=True, upload_to=recipe.models.get_image_path)),
                ("encrypt", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("cook_time", models.IntegerField(default=0)),
                ("serves", models.IntegerField(default=0)),
                (
                    "ingredients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=80), default=list, size=100
                    ),
                ),
                (
                    "steps",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=300), default=list, size=100
                    ),
                ),
                (
                    "users",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(default=-1), default=list, size=1000
                    ),
                ),
            ],
        ),
    ]
