# Generated by Django 3.0.4 on 2020-03-28 00:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('ingridients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), size=None)),
            ],
        ),
    ]
