# Generated by Django 4.2 on 2023-04-30 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="food",
            new_name="recipe_name",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="food_type",
            new_name="recipe_type",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="encrypt",
            new_name="uid",
        ),
    ]
