# Generated by Django 3.0.4 on 2020-03-28 17:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20200327_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='food',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=list, size=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), default=list, size=100),
        ),
    ]
