# Generated by Django 3.0.4 on 2020-03-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20200328_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='food_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
