# Generated by Django 3.0.3 on 2020-04-01 19:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20200331_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), default=list, size=1000),
        ),
    ]
