# Generated by Django 3.0.3 on 2020-04-20 04:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20200416_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='encrypt',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
