# Generated by Django 3.0.3 on 2020-04-20 04:25

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Recipe = apps.get_model('recipe', 'Recipe')
    for row in Recipe.objects.all():
        row.encrypt = uuid.uuid4()
        row.save(update_fields=['encrypt'])

class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_recipe_encrypt'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
