# Generated by Django 3.0.3 on 2020-04-20 04:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20200419_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='encrypt',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
