# Generated by Django 3.0.3 on 2020-04-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(default='', max_length=100)),
                ('from_user', models.CharField(default='', max_length=80)),
                ('to_user', models.CharField(default='', max_length=80)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
