name: Docker

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  #workflow_run:
  #  workflows: [Django]
  #  types:
  #    - completed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: us-east-2
        role-to-assume: arn:aws:iam::658340567265:role/github-actions-role
        role-session-name: GithubActionsSession

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    #- name: Login to Docker Hub
    #  uses: docker/login-action@v2
    #  with:
    #    username: AWS
    #    password: 658340567265.dkr.ecr.us-east-2.amazonaws.com

    - name: Login into Docker
        run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 658340567265.dkr.ecr.us-east-2.amazonaws.com

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: 658340567265.dkr.ecr.us-east-2.amazonaws.com/community-cookbooks:latest